# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_cartgoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartgoods',
            name='goodsid',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cartgoods',
            name='num',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cartgoods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
