# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_auto_20180919_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresspreson', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('addressphone', models.CharField(max_length=11)),
                ('status', models.BooleanField(default=False)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
    ]
