# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_auto_20180921_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='addressid',
            field=models.IntegerField(),
        ),
    ]
