# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_auto_20180921_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='goodsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods'),
        ),
    ]
