# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0013_auto_20180921_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'permissions': (('show_goods', '查看商品管理'), ('insert_goods', '添加商品'), ('edit_goods', '修改商品'), ('del_goods', '删除商品'))},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'permissions': (('show_types', '查看商品分类管理'), ('insert_types', '添加商品分类'), ('edit_types', '修改商品分类'), ('del_types', '删除商品分类'))},
        ),
        migrations.AlterModelOptions(
            name='userorder',
            options={'permissions': (('show_orders', '查看订单管理'),)},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('show_users', '查看会员管理'), ('insert_users', '添加会员'), ('edit_users', '修改会员'), ('del_users', '删除会员'))},
        ),
    ]
