# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0015_auto_20180925_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userorder',
            options={'permissions': (('show_orders', '查看订单管理'), ('del_orders', '删除订单'))},
        ),
    ]
